# Generated by Django 2.1.4 on 2019-01-01 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20190101_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='id_no',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
