# Generated by Django 2.1.4 on 2018-12-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('er_no', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('college_name', models.CharField(max_length=250)),
                ('codeforces', models.CharField(max_length=100)),
                ('codechef', models.CharField(max_length=100)),
                ('spoj', models.CharField(max_length=100)),
                ('hackerrank', models.CharField(max_length=100)),
                ('hackerearth', models.CharField(max_length=100)),
            ],
        ),
    ]
