# Generated by Django 2.1.5 on 2019-01-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='github',
            field=models.CharField(default='abhinavsharma629', max_length=100),
        ),
    ]
