# Generated by Django 2.1.5 on 2019-01-29 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studentdata_github'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeforces', models.CharField(max_length=100)),
                ('codechef', models.CharField(max_length=100)),
                ('spoj', models.CharField(max_length=100)),
                ('hackerearth', models.CharField(max_length=100)),
                ('github', models.CharField(max_length=100)),
                ('er_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentData')),
            ],
        ),
    ]
