# Generated by Django 2.1.5 on 2019-01-29 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='er_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.StudentData'),
        ),
    ]
