# Generated by Django 2.1.5 on 2019-01-29 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20190129_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='er_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='student.StudentData'),
        ),
    ]
