# Generated by Django 2.1.5 on 2019-01-30 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20190129_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='github',
            field=models.CharField(max_length=100),
        ),
    ]
