# Generated by Django 2.1.5 on 2019-01-30 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20190130_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='codechef',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='codeforces',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='github',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='hackerearth',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='spoj',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
